name = "kabaddi-timer"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSession"

[[migrations]]
tag = "v1"
new_classes = [ "GameSession" ]

[build]
command = "npm run build"

[env.development]
compatibility_date = "2024-11-01"

[env.production]
compatibility_date = "2024-11-01"